name: Build OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天构建一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set up OpenWrt SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file python3

    - name: Clone OpenWrt source code
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure OpenWrt
      run: |
        cd openwrt
        make menuconfig # 在这里可以自定义你的OpenWrt配置

    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/

